class Zone:
    ID = "id"
    NAME = "name"

    def __init__(self) -> None:
        self.salesdep = "Отдел продаж"
        self.servdep = "Отдел заботы"
        self.reciep = "Рецепция"
        self.hall = "Холл"
        self.bar = "Бар"
        self.cash = "Касса"
        self.kidclub = "Детский клуб"
        self.locker = "Раздевалки"
        self.gym = "Тренажерный зал"
        self.spa = "СПА"
        self.marts = "Клуб единоборств"
        self.shower = "Банный комплекс"
        self.ant = "Антресоль"
        self.tech = "Техническая зона"
        self.pool = "Бассейн"
        self.entry = "Вход"
        self.kidclubcenter = "Детский клуб (центр)"
        self.kidclubsport = "Детский клуб (спорт)"
        self.kidclubedu = "Детский клуб (учебный)"
        self.gpyoga = "ГП Йога"
        self.gp1 = "ГП 1"
        self.gp2 = "ГП 2"
        self.inbody = "Инбади"
        self.mlocker = "Раздевалка (мужская)"
        self.flocker = "Раздевалка (женская)"
        self.staffarea = "Служебное помещение"
        self.stairs = "Лестница"

    def __str__(self) -> str:
        return "zone"
